version: '3'

services: 
  app: 
    image: node:16
    command: bash -c "npm install && npm start"
    ports: 
      - '3001:3001'
      - "3306:3306"
    volumes: 
      - ./:/usr/app
    working_dir: /usr/app

  