version: "3"

services:
     app:
          image: node:18
          command: bash -c "npm install && npm run start:dev"
          ports:
               - "3001:3001"
          volumes:
               - ./:/usr/app
          working_dir: /usr/app
          container_name: euterpe_api
